# contents of a minimal pyproject.toml 

[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build" 

[project] 
name = "example_package_YOUR-USERNAME-HERE" 
version = "0.1.0" 
dependencies = ["numpy"]
